name: release

on:
  release:
    types: [published]

env:
  APP_NAME: 'APPNAME'
  NIM_VERSION: 'stable'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    needs: before
    steps:
      - uses: actions/checkout@v1
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ env.NIM_VERSION }}
      - run: nimble build -Y
      - name: Archive files
        run: nimble archive
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: 'dist/${{ env.APP_NAME }}_*.*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-packages:
    runs-on: ubuntu-latest
    needs: before
    strategy:
      matrix:
        format:
          - deb
          - rpm
    steps:
      - uses: actions/checkout@v1
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ env.NIM_VERSION }}
      - run: nimble build -Y -d:release

      - name: Set envs
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\/v/}

      - name: Move file
        run: mv bin/${{ env.APP_NAME }} .

      - name: Set envs
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\/v/}

      - uses: kentik/pkg@v1
        with:
          name: ${{ env.APP_NAME }}
          version: ${{ steps.vars.outputs.tag }}
          arch: x86_64
          format: ${{ matrix.format }}
          package: .github/package.yml

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: 'dist/${{ env.APP_NAME }}_*.*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
