name: release

on:
  release:
    types: [published]

env:
  APP_NAME: 'APPNAME'
  NIM_VERSION: 'stable'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ env.NIM_VERSION }}
      - run: nimble build -Y
      - name: Archive files
        run: nimble archive
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: 'dist/${{ env.APP_NAME }}_*.*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
